# Academic writing {#ch9_writing}

This chapter has some activities to help with your academic writing. You do not have to complete these - it is entirely optional to do so.

## Evaluation in introductions {#eval_intro}

The activities in this section are designed to help you improve your evaluation in the introduction of your RM2 report (and your dissertation). To re-cap from RM1, the purpose of your introduction is to provide a rationale for your study and answer the **WHY** question; why is your study worth doing? You want to sell your idea to the reader, using existing literature to show how you are building on the evidence that is there.

Although 'identifying the gap' is something that is often key in quantitative research, building a rationale is not exactly the same in qualitative research. This is because qualitative research tends to be very much situated in the context of the particular study (i.e. why is this particular research topic or question important in this context/with this group). Regardless of whether you include a gap or not (you still can), you should convey to your reader **why** your study matters (or why a gap you've identified is important to explore). 

**Things to do and things to avoid**
  
  1. Avoid doing one study per paragraph – instead, build your arguments using multiple sources
  2. Avoid describing previous studies in a lot of detail – instead, show how your study builds on them
  3. Avoid critiques that your study cannot answer - instead, focus on aspects that your study will address
  4. Just because something is never done before, doesn't make it worth doing; show with evidence why we should do the study.



### Activity 1: Top tips and rationales in published papers

**Tip 1: Show how your study builds on existing literature**
When you are building your rationale, try to use multiple studies to show your reader what the current context of the literature is, and how your study is expanding that knowledge. What new is your study bringing? How is it expanding on existing studies?

If you look at these paragraphs from [Robertson et al. (2018)](https://www.sciencedirect.com/science/article/pii/S1750946717301277){target="_blank"}, they are building the rationale for their study by showing how it expands on existing literature:

::: {.callout-note icon=false}

## Building a rationale

"Kerns and Kendall (2012) published an updated review of the prevalence of anxiety in individuals with ASD, and all studies fell within White et al. (2009)’s original range for anxiety symptoms (11–84%). It should be noted that, of the 24 studies included in the review, only two reported data for  individuals older than 19 years of age (Bakken et al., 2010, Hofvander et al., 2009), which illustrates the need to also focus on adults with ASD in future research (Howlin, 2000)."

"Secondly, as far as we are aware, there have been no qualitative studies investigating anxiety in autism using semi-structured interviews.  Although focus groups and interviews are both good data collection methods for qualitative data, there is evidence that individual  interviews tend to elicit a broader range of discussion points (Guest, Namey, Taylor, Eley, & McKenna, 2017). Again, this further extends the previous investigation conducted by Trembath et al. (2012)."
:::

**Tip 2: Focus your criticism**

When you are critically evaluating studies in your introduction, make  your criticism focused on things that your study is addressing. This  helps you build the rationale. For example, for the RM2 report, don't  focus on the sample size and generalisability of existing studies in your introduction, because these are not things that your study will actually be able to address. Instead, focus on gaps/problems your study can address.

If you look at this paragraph from [Toivo & Scheepers (2019)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0210450){target="_blank"}, they are identifying a gap/problem in existing literature and showing how the new study is addressing this:

::: {.callout-note icon=false}

## Focusing cricitism

"A potential issue in the above SCR studies (as well as in some of the  cognitive studies discussed earlier) is that the stimuli were not very  tightly controlled in terms of lexical variables (length, frequency,  abstractness, etc.), or in terms of syntactic/pragmatic complexity when multi-word phrases were used. This, again, introduces a number of  potential confounds (both within and across languages), making it  difficult to separate effects of emotional resonance from those related  to cognitive effort in word processing. In the present study, we aimed  at eliminating such potential confounds by matching our stimuli on a  number of lexical variables–as was done in the ERP studies discussed above [22, 23]–and by avoiding the use of translation equivalents."

:::

**Tip 3: Draw arguments from related topics. **

Sometimes if your topic has not been studied much, it might be difficult to create an evidence-based rationale for your research question. In this case, you can draw logical parallels from related topics/domains. Remember to explain to the reader why you would expect the findings to generalise across the related topics.

If you look at this paragraph from [Mahrholz et al. (2018)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0204991){target="_blank"}, it acknowledges that evidence on what they are looking at is scarce in voice perception, but the same effect has been found in face perception: 

::: {.callout-note icon=false}

## Drawing arguments from other topics

"Similarly, looking at reliability of personality traits across presentation durations, Willis and Todorov [40]  found that ratings of trustworthiness, competence, likeability,  aggressiveness, and attractiveness for faces, showed moderate to strong  positive correlations after 100 ms, 500 ms, and 1000 ms, when compared  to ratings made without time constraints. Only participants’ confidence  in their own judgements increased as a function of duration. Likewise,  again using photographs of faces, Bar et al. [33]  reported medium positive correlations between ratings at 39 ms and 1700  ms. The authors indicated that the lower threshold was sufficient for  reliable assessments of threat but not intelligence, supporting the  theory that rapid first impressions serve as a mean of self-preservation  and help determine appropriate approach-avoidance behaviour [1, 33, 38].  The idea being that it should not require much information to decide  whether a stranger is friend or foe. Finally, Todorov and colleagues [39]  obtained a similar finding, again for faces, showing 33 ms of exposure  to be sufficient to distinguish between trustworthy- and  untrustworthy-looking stimuli. Whilst correlations with control ratings  improved between 33 ms and 100 ms, increased exposure duration did not  significantly increase the correlations.

In voice research, though there are limited studies that consider the  reliability of personality judgements across varying lengths of stimulus  types, similar findings have been shown as in face research."
:::


### Activity 2: Active reading

When you are reading journal articles, make sure to take notes and think of how each article can be used to build your rationale in the introduction. [Here is a resource you can use to help structure your notes](https://gla-my.sharepoint.com/:w:/g/personal/wilhelmiina_toivo_glasgow_ac_uk/EXPNU5j4pQhKvRMYVx8dBvcBs85f4Z8q1V21wSokGOIbCA?e=eg7zd0){target="_blank"} about the studies you are going to use for your introduction.

## Evaluation in your analysis section {#eval_analysis}

### Activity 1

[Complete this activity](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EUiKwKgdqr1CsLeOxy5O42kBGNLxmbdeTqANFRu0caPcBA?e=BpEpBb){target="_blank"} to improve your evaluation for your thematic analysis, (as well as the discussion section).We ask you to compare two published papers against some of the qualitative report ILOs.


## Evaluation in discussions {#eval_discussion}

In this section, we aim to provide some guidance about how to go beyond description in your writing. We will specifically focus on the Discussion section for your RM2 qualitative report here, but
you can apply this to other types of writing. In particular, it should be helpful for you as you proceed to your dissertation.

### What were your findings?
In your discussion section, start off by telling us what you found in your analysis. However, the key thing to think about here, in terms of evaluation, is to relate your findings to the wider research. It will be likely a good idea to consider on a theme by theme basis (if you are doing themes with no sub-themes) or on a subtheme basis (if you have one theme with 2-3 subthemes).

**Some things to consider:**
  
  * What did you find? What was your specific contribution?
  * Thinking about your findings, what are the similarities and differences from other research findings/theory? Why might this be the case?
  * Situate your findings within the broader context  - tell the reader about why your findings are important. This can help a reader understand the importance of the results.
  * Do your findings challenge existing research? If so, in what way? 
  * Can you bring in any critical thinking?
  
#### Activity 1

Read the paragraphs below from [Crompton et al., (2020)](https://journals.sagepub.com/doi/full/10.1177/1362361320908976?fbclid=IwAR0tMsMbmeATwp5RpoKA-yqUr3QzyHuBSuy00uMAvlqZepaS4Pv_48VgQjA){target="_blank"} and think about what the authors are communicating, with a view to considering the points above.

In particular, identify:

  * How the authors summarised their results
  * The contribution of the themes to the evidence base
  * How the authors discuss their results in relation to existing research
  * How the authors relate their findings to theory
  * How the authors link the findings to 'broader issues'
  
::: {.callout-note icon=false}

## Study 1: Crompton et al., 2020

This study aimed to examine the experiences of autistic adults spending time with autistic and non-autistic family and friends using a thematic analysis framework. Social relationships are an important, though often complicated, part of autistic people’s lives. Previous research has tended to focus on autistic people’s relationships with (assumed) non-autistic friends and family. Here, we specifically contrasted relationships across and within neurotypes. The analysis revealed three themes: cross-neurotype understanding, minority status and belonging. The themes help us understand why relationships between autistic and non-autistic people might be so challenging, and how relationships between autistic people are different.

The results align with previous research on the challenges that autistic people face when interacting with non-autistic others, but highlight that interactions with other autistic people are fundamentally different. All participants reported that spending time with non-autistic family and friends involved specific difficulties, which were not experienced when interacting with other autistic friends and family. This aligns with the double-empathy theory of autism which suggests that autistic and non-autistic people have a mutual difficulty in understanding and empathising with one another due to differences in how each person understands and experiences the world, rather than because of a communicative deficit on the part of the autistic person (Milton, 2012). Neurotypical people have been shown to overestimate how ego-centric their autistic family members are (Heasman & Gillespie, 2018), and overestimate how helpful they are to autistic people (Heasman & Gillespie, 2019). Our findings suggest that this translates into real-world difficulties in interactions with neurotypical friends and family that may affect the mental health, well-being and self-esteem of autistic people.

:::


### What are the implications of the study?

In addition to theoretical implications you would discuss in a quantitative study, there is scope to discuss broader implications here. Try not to go too far in these implications (e.g. saying that the NHS/University could make changes to how they run mental health services...this would require a much more extensive body of work).

**Some things to consider:**

  * How could these findings be applied to real-life situations?
  * What impact might this have for society in the future (even if with the caveat that it would depend on future research)?
  * Can you back up your assertions with reference to the literature? Arguments here are much stronger if you are able to cite papers to support.
  
#### Activity 2

Read the paragraph below from [Robertson et al. (2018)](https://www.sciencedirect.com/science/article/pii/S1750946717301277){target="_blank"} and think about how the authors have communicated the implications of the research.

In particular, identify:

  * What the implications of the research are
  * How the authors link the findings to practical suggestions
  * How the authors back up these suggestions to the existing literature base
  
::: {.callout-note icon=false}

## Study 2: Robertson et al., 2018

There are a number of potential clinical applications for the findings detailed in this paper. They echo the modifications that are already undertaken for anxiety interventions designed for children and adolescents with ASD (Walters, Loades, & Russell, 2016). For example, it may be important to include support for individuals undertaking an intervention for their anxiety. This has already been identified as helpful in anxiety management interventions for children with ASD (Sofronoff et al., 2005), but the evidence here suggests that this might also be the case for adults. Furthermore, as adults reported feeling that they enjoyed interacting with other autistic people, it would be important to test whether running autism-only groups in terms of anxiety interventions helps outcomes or other aspects related to the feasibility of anxiety management programs (e.g. retention of participants).

:::

### Limitations

All research will have limitations  - there is never going to be a perfect study. Research is about weighing up the options and choosing the best design for the specific question we want to answer. Remember that qualitative research is not automatically limited because it is not quantitative. Therefore, be very careful not to use criteria we have for quantitative studies (e.g. generalisability, reliability, small sample sizes) and apply them to qualitative studies. Doing so would be similar to critiquing a behavioural study for not asking participants about their experience of interacting with the stimuli ;)

**Some things to consider:**

  * Do you think the quality, source, or types of data (or the analytic process) might have affected the methodological integrity in some way? If so, how?
  * Remember to link your limitations to the evidence base. This makes your argument much stronger than if you do not cite to back your points up.
  * If you want to mention generalisability, perhaps consider the concept of transferability instead, which is much more relevant to qualitative.
  * Try to aim for depth rather than breadth here - it's much stronger to have two points addressed comprehensively than have 12 limitations, each covered in a single sentence (you don't want to make your discussion section a limitations-fest!).
  
  
#### Activity 3

Read the paragraph below from [Toivo & Scheepers (2019)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0210450){target="_blank"}. Although this is not a qualitative paper, the following paragraph exhibits many of the strengths noted above.

In particular, identify:

  * What was the limitation observed?
  * How do the authors discuss this limitation, and consider the effect it might have had?
  * How do the authors back up their arguments with evidence from the literature base?
  
::: {.callout-note icon=false}

## Study 3: Toivo et al., 2019

One concern might be that we did not explicitly control for L2 proficiency in our sample of bilinguals, which is likely to affect cognitive effort in processing L2. However, all of our bilingual participants (a) self-reported to be highly proficient in English, (b) were Glasgow University students using English as their language of study, and (c) had been living in an English-speaking country for minimum of three months (average: two years and four months) when the study was conducted. Together with the fact that post-trial word recognition rates were well above 90% across participant groups and conditions (Fig 2), we do not believe that variation in L2 proficiency was large enough to have a major impact on our results. That said, we agree that proficiency should ideally be controlled for in future research, e.g. by adding a suitable measure as another person-specific covariate in the analyses. Previous research had identified proficiency as a potential mediating factor of perceived emotionality in the Bilingualism and Emotions Questionnaire [50], and it had also been suggested that bilinguals with close-to-native proficiency in L2 show similar affective processing in L1 and L2 [19].

:::



### Anything else?

The points above are the key components that we would expect to see in a Discussion section, with some guidance on how to go beyond description. However, you might also consider strengths and future research. It's also good to include a brief conclusion. You won't have the word count available to go into the same detail as in these papers, so try to use the examples above to really focus on what you can incorporate within your Discussion section to strengthen your evaluative writing.




